/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MaterialSphere: typeof import('./src/components/MaterialSphere.vue')['default']
    MaterialTorusKnot: typeof import('./src/components/MaterialTorusKnot.vue')['default']
    MySphere: typeof import('./src/components/MySphere.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheExperience: typeof import('./src/components/TheExperience.vue')['default']
  }
}
